### ISSUE TITLE
Happy Day & No Server Reset for Private Servers!

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#161]
Since I was thinking the "Staying Alive Sale" was over maybe you can introduce "Happy Day" where you can get 24 hours of Happy Hours and I would think the price for the Happy Day can be 1,000 Kreds and if you need to do the math @jacob-grahn 50 kreds*24= 1,200 but I would think maybe since we're buying a lot of Happy Hours it'd be nice if it can be 1k at least imo and I would like this to be restricted to Private Servers only because the next topic is that would it be possible for only Derron-Isabel/Tournament are public servers can get the server reset and Private Servers get no reset cause honestly I don't see why we get the reset other than the free Happy Hour we get after the servers are back.

**Comment by bls1999** [comment]
This is a nice idea for private servers!  Pros and cons as I see them:

Pros:
 - Solves the issue of the staying alive sale being done
 - Solves the issue of happy hours being hella expensive

Cons:
 - @jacob-grahn doesn't get as much revenue for HH purchases
 - Simmers/macroers get an entire day to earn double exp while normal users earn normal.  This could be fixed by adding a maximum exp cap for happy days.

If this were to be implemented, I'd want it to only have a 10% (or less) chance of occurring when the servers restart.  Theoretically, that would mean a happy day happens 3 times in a 30-day private server purchase.

With a method to moderate how much exp users get, this could be a very successful idea.

**Comment by LP-PR2** [comment]
@bls1999 why limit the amount of exp earnt when you're spending money to earn the exp? if you don't want any benefits at all for simmers/macroers.. remove the vault of magics completely.

**Comment by bls1999** [comment]
@LP-PR2 how does putting restrictions on simmers'/macroers' already OP exp gain translate to removing the vault of magics completely?  There are people that buy things that aren't simmers/macroers.

**Comment by LP-PR2** [comment]
@bls1999 Because there is still the option to trigger a Happy Hour, and you can freely buy a full day of Happy Hours already.. Why limit it if you add a "Happy Day" when you've been able to buy unlimited happy hours since VoM opened?

**Comment by bls1999** [comment]
@LP-PR2 because now the simming/macroing restrictions are removed, which in turn lets simmers/macroers gain a ton of EXP.  @jacob-grahn said he was looking for a way to reward regular players for not simming/macroing, and this seems like a good solution.

**Comment by LP-PR2** [comment]
@bls1999 so macroing the people who are choosing to pay for a service sounds good to you?

**Comment by LP-PR2** [comment]
Could you imagine spending $100 for a limit? That's what you are saying @bls1999.. If you ever ran a game with DLC i would fucking uninstall and quit if that's your idea of a good solution.

**Comment by FearsPR2** [comment]
I agree with LP; a happy day if purchased for however much money should have no cap. However if we're talking about a randomly triggered happy day that wasn't purchased (if that would even be a thing) then I could agree with a cap on exp.

**Comment by bls1999** [comment]
I was under the impression that the happy day would be a random occurrence only on private servers.  If that's not the case, I'm very opposed to the idea unless the price is significantly more than a happy hour.

It seems to me that keeping it as a random occurrence would be the best possible option to keep it fair for non-simmers/macroers, since it would include a cap on EXP.

**Comment by Jmarroqu** [comment]
I don't tell you how to do your staff even tho you're doing a bad job of it but ofc imo but you're no simmer/macroer and Jiggmin would get a lot of $ because like me or at least who isn't poor can buy Happy Day everyday and if that's the case he'd be making a shit more $ than buyin 1 hh but let's face it at most people put 10-12 Happy Hours which it was on the sale so 12*12 = 144 now 50*12= 600 so you see why I want a Happy Day yeah he would put it at a lost but if he looks it at in the long run he would make more I don't get why company/owners think of $ right now when you should be doing it by the long run if you introduce Happy Day I would bet that a lot of players would get a job, put $ since they can macro all day (mostly) and having a Happy Day that doesn't HAVE a CAP of EXP he would be making a lot more. Anyways, I have to get ready to work and @jacob-grahn please think about it and don't listen to Bls1999 in the long run you'll make more $ and beside if you do it I'll buy it a lot I know that for sure.

**Comment by bls1999** [comment]
@Jmarroqu @LP-PR2 It's disappointing that my opinions are met with such hostility from the both of you.  I would never attack you based on your opinions because I recognize that we're different people with different perspectives.  I value your opinions and think it's extremely healthy to discuss this; However, I expect from now on that you both will keep your arguments and discussions civilized and respectful.

That being said, I'd like to respond to the content Colin's arguments point-by-point.

Firstly, @Jmarroqu, in your opinion, how many Kreds would be a reasonable amount be to pay for a Happy Day?  I recognize that I can't give an accurate opinion without knowing this.

You had previously asked about Happy Hours stacking (issue #140), and Jiggmin implemented this.  I don't have access to your order history so I have no idea if you've bought enough Happy Hours to have them start stacking.  What I do know is if Jiggmin implemented Happy Days, the price of one Happy Day would need to be the same price as 24 Happy Hours in order for Jiggmin to make a profit.

Unless I'm not understanding line 7 of your message, I don't see how Jiggmin adding an option to buy a Happy Day would motivate PR2 players to get jobs.  Can you explain that a bit?

**Comment by Jmarroqu** [comment]
@bls1999 Because of the sale being gone youll pay 1, 200 kreds that's a shit ton kreds so why not place 1k kreds its still a lot

**Comment by bls1999** [comment]
@Jmarroqu this is why I feel that Happy Days should be a random occurrence if implemented at all.  No one would want to pay $100 every time they want a Happy Day, but Jiggmin wouldn't make any profit otherwise.  If someone wants a Happy Hour, they can activate one.  If they want another one, they can activate that one.

In my opinion, a Happy Day, if implemented, should be a special random event that can't be controlled by purchases from the Vault of Magics.  It's enough to be able to activate a Happy Hour at will.

**Comment by LP-PR2** [comment]
@bls1999 why would you want to charge more for a happy day? Is $100 not enough of a discount from the $120 it would cost (assuming kreds are $1 per 10). It would be pointless to charge more than that, because then you would just stack 24 hhs for cheaper than a happy day..

Also I'm sorry for acting so 'negative' towards your responses, but it appears to me that you're not favouring the majority of the PR2 population when it comes to this suggestion, not to mention the fact that you didn't even read the OP about how it would be a paid feature, not random. So I don't think you're in a place where you can judge our responses to your ignorance.

**Comment by Jmarroqu** [comment]
@bls1999 You said no1 would spend $100.. i think if jiggy does this Happy Day everyone would. Also, no1 buys 12+ HH'S so you saying Jiggmin would lose money? No? cause if you do math if Happy Day was a thing with 1,000 kreds and at most 12 hh a person would do not TOTAL in before you say that stupid reason. He/She would spend 600 kreds that's 400 kreds profit for Jiggmin. I think if he does how many simmers would keep doin it everyday cause I would spend $500 for 5885 kreds.. so yeah. THIS THREAD IS FOR REQUESTING A HAPPY DAY WITH THE PRICE OF 1,000 KREDS WITH NO EXP CAP OR BEING RANDOM. GOT IT BLS1999?

**Comment by bls1999** [comment]
@jmarroq so what's stopping them from just buying 12 happy hours and having them stack instead of the happy day?  If you bought a happy day when you were only going to use 12 hours, that's a huge waste of money.

Additionally, and I'm not trying to be rude, but the reason it's hard for me to accurately understand your argument is because your paragraphs have so many words mashed together in no particular order or sentence structure.

@LP-PR2 the majority of the population doesn't even need this.  The only benefit this holds is for simmers/macroers.  My "ignorance" stems from @jacob-grahn's want to reward normal players for not being simmers/macroers.  Meanwhile, it seems like you guys are trying to remove all EXP restrictions so that you can get as much EXP as you can.  The game is not just about the simmers/macroers; there's a population of actual players that would think this is just as unfair as I do.

Again, I believe this would be better suited as a random private server occurrence with an EXP cap.  It gives a nice perk to server owners and it isn't extremely OP.  I continue to believe that this would be something people would completely ignore; why pay $100 when you're only going to use $60 of happy hours?  This is only cost effective for the consumer if they are on PR2 for more than 20 hours.  It's simply a waste of money; why pay more for the exact same thing?

**Comment by Jmarroqu** [comment]
First paragraph: How is it a waste of $ if you put the Happy Day smartly it wouldn't be a waste and yeah there's always 23 hours and not 24 but that's WHY I said no Server Reset on Private Servers for that reason for 1 stupid HH that u get free/u waste = EVEN, dumbass. 

Second paragraph: If you don't like the way I type than get the fuck out of this thread.. simple as that.

Third paragraph: Are you this stupid? LP and I are both great Trappers, Racer, Glitchers we dabble on Frust and do Campaign but we MACRO full time so please don't say we're just "simmers/macroers" when we're more and everyone else too that's macroing/simming. 

Fourth Paragraph: If you don't stop requesting that idiotic request I swear to god I'll find the Holy Book and throw it at you I try not to get into this Pr2 Drama but sometime you're just so annoying I can't help it.

**Comment by bls1999** [comment]
@Jmarroqu Your rude words and personal attacks are not appreciated.  If you have a valid argument that doesn't include attacking me, I'd love to hear it.

**Comment by Jmarroqu** [comment]
@bls1999  http://prntscr.com/i95c3e There's no $60 option but i'll play dumb and say you mean 3x $20 which will be in total 675 kreds now / that by 50 kreds/hh = 13.5 HH's so 13 so how is it the same amount as doing 24 HH's when in fact that's 1,200 kreds? We only get $5/50 kreds, $20/225 kreds, $100/1,150 kreds, $250/2,900 kreds, and $500/5,825 kreds so if you want us to buy the full amount for 24 Happy Hours then that's $105 BUT because of the Server Reset HOW CAN WE LEGIT FAIRLY USE 24 HOURS when its actually 23 hours UNLESS we do it after the server reset come back. Anyways, since numbers don't like @bls1999 unless you can't read them it's fair for Jiggmin to make it 1,000 kreds and gets rid of the Server Reset for Private servers and doesn't do the EXP CAP/Random ones because we CAN'T ABUSE EXP the AMOUNT of EXP WE GET IS WHAT WE GET FROM THE ALTS WE USE FOR EXAMPLE; If I use Rank 70, 67 and 66 that's 75+72+71+25(level completed) = 243 exp x by 5 because of the 4 EXP HAT = 1,215 WITH NO HAPPY HOUR or WITH HAPPY HOUR 2,430 and SINCE we DON'T GET THE CAPTCHA EXP BONUS WE' AINT GAINING MORE EXP SO ITS NOT BROKEN

**Comment by woodenstix** [comment]
>macroing now can be easily done
>begging for more exp

this is it guys, pr2 community mentality at its finest

**Comment by bls1999** [comment]
@jmarroqu …what?

I'm not talking about actual purchases of Kreds on Kongregate.  I'm talking about the vault of magics purchases you make with kreds you already have.  I am not by any means saying buying 24 separate Happy Hours will be more cost effective than a Happy Day in your proposal.  What I'm saying is the only people who will buy a happy day are macroers; smart consumers are not going to 1) play PR2 for literally 24 hours straight, 2) spend that much money on PR2, and 3) buy more than one or two Happy Hours at a time.

Your numbers are simply not relevant to the conversation.

**Comment by FearsPR2** [comment]
At the end of the day, Colind just wants to gain as much exp as possible, and if he's willing to spend that much on a happy day purchase, then there surely could be others that would want to do the same. As PR2 is right now there probably wouldn't be many purchases of it, but who knows maybe it'll become a very good option for exp gains.

With that having been said, Colind is also basically paying for the servers to be up, as I don't see anyone else putting in nearly as much as he does to keep the servers running (i'm sure Jiggmin is glad he's making some money still out of PR2).

@bls1999 I know it's hard to accept the fact that PR2 isn't what it once was, and is more of an EXP grind game now, but instead of trying to limit people's EXP, why not fully embrace it and hope that the news of PR2's new rules/system trickles down and reaches some old school players and brings back popularity.

Even on the most popular server (Derron ofc) still takes ~10 minutes to find a full 4p race on campaign. I think it's fully for the benefit of PR2 in it's entirety, to try to give any reason for old players to return and enjoy the game again, and I think with the addition of Macroing/Happy Day gives a damn good incentive for people to come back and start working on those gains.

**Comment by Jmarroqu** [comment]
Did you know that $=kreds and kreds=$ and therefore the value of what you're saying is mathematically incorrect. Also, I'm done talking to a Staff that just wants to RIPs on Players of what they want to do on their own Pr2 time and spend whatever $ they want on it. The fact is this In order to get EXP in any Pr2 maps you need accounts the rank and exp hat on the acc will determine the exp you'll get per sim so therefore if NOTHING is being "boosted" why would u cap it when nothing being altered you can't get more EXP because of Happy Day nor will it be the difference if you buy 24 HH's every hour so please stop saying my math is nothing when it just proves that you're incapable to understand my Point of View. I get that now that Server Reset might not able to do because it's a requirement to clean and help the server out but The Happy Day still stands. If I just want to buy a "Happy Day" and not just buy 24 HH's and since it "takes time" to load and give the HH's and u have to go back to the VoM and do it again its just a hassle and waste my time when Jiggmin can just make an option for people who can just buy 24 HH's.

@jmarroqu …what?
 when in all honestly we can't do the same for you

@jmarroqu …what?

I'm not talking about actual purchases of Kreds on Kongregate.  I'm talking about the vault of magics purchases you make with kreds you already have.  I am not by any means saying buying 24 separate Happy Hours will be more cost effective than a Happy Day in your proposal.  What I'm saying is the only people who will buy a happy day are macroers; smart consumers are not going to 1) play PR2 for literally 24 hours straight, 2) spend that much money on PR2, and 3) buy more than one or two Happy Hours at a time.

Your numbers are simply not relevant to the conversation.

**Comment by ImProficient** [comment]
Solutions:

 Make a macro in which automatically buys HH every hour except server reset. LOL

 Make a VoM for 6 hour Happy Hours (so the price isn’t just for simmers/macroers but regular players should be able to enjoy Happy Hour to it’s not like only simmers can buy it. Atleast they pay up for such an advantage, just like every other game in existance. And is it really that much of one? LOL

 How about instead of players bashing sim ideas and simmers bashing race ideas, we all think of a middle ground solution. Easy

**Comment by ImProficient** [comment]
I hope they implemented something or someway to improve the race community to ❤️

**Comment by ImProficient** [comment]
So i vote you you should compromise of a shorter time period Happy Hour but longer then 1 Hour, maybe make it Happy Time for 3, 5, or 6 hours for a fair price

**Comment by ImProficient** [comment]
And I slightly don’t agree on no server reset for private servers, some people don’t buy HH for then 😋 but I don’t use private servers so..

**Comment by bls1999** [comment]
@Proficient @Jmarroqu I've said my piece.  I'm obviously not going to convince Colin that my idea is better, and Colin won't convince me that his is.  I'll wait for @jacob-grahn to share his thoughts.

**Comment by woodenstix** [comment]
@bls1999 If you're the staff member that does NOT mean you know everything. This would benefit everyone except you because you hate macroers and you know it!

**Comment by bls1999** [comment]
@woodenstix I don't think I ever claimed to know everything.  I don't.  The same can be said about anyone else on this thread.  We've all said our piece and I'm waiting for @jacob-grahn to weigh in.

**Comment by Jmarroqu** [comment]
You say that my idea isn't the best yet with math/numbers it's proven to be so how can you even fight about that? The fact that we get just say a basic simmer player vs a Campaign player let's say they get 1,000 exp with their alts and the Campaign vs players and for example the map Zerostar is what you can do under 20 sec so say you can get at most 300 exp for being number 1 to win against 3 other players 300/20sec x6 = 1,800 exp for 2 mins compare to the simmer side they get 1,000 for two mins. It's a fact that racers can beat a simmer and let's dumb this down to your level @bls1999 let's say 200/20sec x6 = 1,200 again beats the average simmer.. so you're sayin simmers gets more exp when racers can in fact get more EXP than simmers (just depends on the map) The only reason I do x6 is because 20 sec x6 = 2 mins tho it's prob about x7-8 bc simming takes 2mins but about a min more for everything to load or if ur fast enough 2.5 mins per sim. THESE ARE FACTS NOT OPINIONS SO THEREFORE HOW CAN YOU ARGUE THIS?!?!?!

**Comment by bls1999** [comment]
@Jmarroqu If/when you decide to rephrase that message to be civilized, I'll respond.  Until then, your attacks on my intelligence and character are nullifying your arguments.

**Comment by FearsPR2** [comment]
In conclusion:

Regarding happy hours, Jiggmin should make it so that when you click on purchasing a happy hour through VoM, you get the option of 1 hour, 2 hours, 4 hours, 8 hours, 12 Hours, 24 hours. All at varying prices. 

Preferably the larger purchases could come with a sort of bulk deal (that’s the way Kong kreds work as wel) as well as having no cap on EXP. 

I think it would also be cool for there to be a very rare chance of a “Happy Time” spawn on random servers like the happy hours do. Maybe not even a full day but either the 2 hour, 4 hour, 8 hour, or 12 hour variant of the “Happy Hour.”

Just my personal opinions of course, I’m curious as to everyone’s opinion on the 3rd paragraph of this post.

**Comment by Jmarroqu** [comment]
@bls1999 In my opinion, my math shows that you're wrong so all I'm asking why do you think you're right when numbers don't lie? The fact that you said "Why should simmers/macroers get more exp" when that's also a lie when racers can beat simmers in exp if you're smart. For example the average simmers will get about 1,000 exp for every 2.5 mins. If a racer that does Zerostar can do it in under 20 seconds so just say they're racing 4 players if you account he win first he'll get about 300 exp so 300 exp x6 = 1,800 exp for 2 mins (not 2.5 mins like simmers) so let's say they get 100 exp lower so 200 exp so 200 exp x6 = 1,200 exp for 2 mins (not 2.5 mins) so even me typing and showing you correct math/numbers how can you say a Racer can not compete with Simmers when they can its just they don't want to try so hard so that isn't the macroers/simmers fault. Anyways, if you feel like that I was "hurting" you because of words you shouldn't even take offense then I am sorry but how would you except to me not get mad at a person who can't comprehend math/numbers/facts that I am saying so with that I'll ask you to reply.

**Comment by woodenstix** [comment]
Facts don't matter, if you're lazy to make a script to buy HH every hour, log in automatically and sim non-stop then your fault. All you're demanding is cheaper exp gain per hour

**Comment by Jmarroqu** [comment]
The fact is this not everyone can write a script so stop assuming everyone can. I only record myself doing 1 sim map with all delays and loop it til I stop it that's fact so since Happy Hour is every hour I am not gonna record myself for an hour just to do a Happy Hour. Why is everyone assuming that the Happy Day is cheaper exp when it's the same for reg Happy Hour? You don't get anymore EXP you get the same amount that is DETERMINE about the rank alts you USE so again you and bls stop writting shit that isn't even about the request I am putting. REQUEST: A option to put Happy Day or what @FearsPR2 a option within the "Happy Hour" for the Happy Time 1, 2, 4, 8, 12, 24. I now understand that the Server Reset being taken off is not an option.

**Comment by woodenstix** [comment]
>using script recording program

Are you mad, that I think your idea is shit? Why are you sensitive about it? You and bls are both in this situation, but it's obvious that you need more exp AFTER MACROING IS ALLOWED. You keep asking for more.

**Comment by woodenstix** [comment]
Maybe ask Mega happy hour, 5x exp? Will that make you happy?

**Comment by FearsPR2** [comment]
@woodenstix I hardly even see you making suggestions for improvements or adding to the conversation, so if you'd butt out, it'd be apprecaited. :ok_hand:

**Comment by Jmarroqu** [comment]
@woodenstix You think I want more EXP? I DO but I'm not asking Jiggmin to give us more EXP just an option to let's buy stack 24 hh's on VoM that's it.. not like i'm asking "Give us Happy Day that includes x10 the exp per hour" I'll still get the same EXP for the 24 hours just the hassle of going to kong and putting multiple HH's takes a few mins like today I put 12 HH's took me 5 mins to put so that's why I want either a OPTION or a "Happy Day" so excuse me for asking Jiggmin about something that you know NOTHING about. I am mad.. who wouldn't be when you've two person trying to twist/turn the words of ur post when it isn't about "earning more exp"

**Comment by bls1999** [comment]
The more I hear about this idea, the more I think it's a bad one.  Obviously the decision is ultimately up to @jacob-grahn and I'm not trying to stir up any problems or offend anyone when I say this, but I just don't support any form of this idea anymore.

**Comment by woodenstix** [comment]
>Your opinion does not matter if I hate you!

Typical pr2 players that are mad LOL!
