### ISSUE TITLE
Difficult to create scripts that use the database

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#204]
@jacob-grahn 

It's not very easy for me to create scripts that use db functions because 1) I have no idea what requests are sent to the db and 2) I don't know the db structure.  Could you release the MySQL queries that are being executed when we do something like this?

`$user = $db->grab_row('user_select', array($user_id), 'Could not find a user with that name.');`

I assume they're in a php file somewhere.

For instance; In this example, I know that `user_select` is the function, `array($user_id)` is what's passed to the function, and `Could not find a user with that name.` is the custom error.  But what exactly does `user_select` do?

Knowing this information would make it a lot easier for people like me to add tools to the game that require custom database functions or queries.

**Comment by jacob-grahn** [comment]
They're stored procedures. At one point I decided to convert all of the queries into stored procedures, but only got about halfway though for whatever reason. It would be generally good from a security standpoint if we converted the rest, because it would prevent sql injection without us having to constantly escape input data.

Where it gets a little tricky is I'm not sure how to go about keeping the db in sync with changes made to this repo. It might be better to transfer all of the queries out of the stored procedures, and into php files. Then we'd set up some other automatic way to prevent sql injection.

**Comment by bls1999** [comment]
It might be more practical to throw the mysql queries into variables in a php file.  Then, you could look into (https://www.w3schools.com/php/php_mysql_prepared_statements.asp)[prepared statements].

**Comment by bls1999** [comment]
I would also like @aaaaaa123456789 to weigh in, because I know that my somewhat limited knowledge of php pales in comparison to his.

**Comment by aaaaaa123456789** [comment]
There is little risk in using prepared queries instead of stored procedures. Both are under control of the server, so the choice has little influence in terms of security.

On the other hand, I can see various antipatterns here:

1. Creating a new function that just calls `mysqli_real_escape_string()`. This is a pointless wrapper. Just call the function directly, what's the point?
2. Letting strings get into integer fields. While you can escape a string, why use a string _at all_ (with all the security risks that it has) when you don't even need one? `$safe_user_id = (string) (int) $user_id` will ensure that `$safe_user_id` contains nothing but digits, at which point no quoting or escaping is needed (since it's just a number).
3. This is the main one: you should really use prepared statements instead of just string queries. While string queries should be able to hold off attacks, they are fragile, and it's only a matter of time before someone finds out how to break out from the escaping characters (Unicode bugs are common — as you should know if you have [an iPhone that now loves to reboot](http://bgr.com/2018/02/15/ios-message-bug-crash-iphone-how-to-fix-ios-11-3-beta/)). Look into the `mysqli_prepare()` function and associated things.


Using prepared statements is a well-known way of avoiding SQL injection without having to move all the logic to the database itself. You should really apply this fix everywhere in the codebase where parameters are involved. (Note that parameters passed to prepared statements aren't escaped at all; the prepared statement engine takes care of replacing them in the correct locations. Read the documentation carefully.)

**Comment by aaaaaa123456789** [comment]
Also, as a general security tip, avoid using strings for data that isn't actually string-like. Values such as numbers, booleans, and the like (and basically anything that isn't actually a string) should be converted to their natural data types as early in processing as possible. Do not assume that user input will be valid in this regard: make sure to check if conversions fail and abort early if they do. This applies even to data that is received as a string but shouldn't actually be a string, such as query string parameters that contain numeric IDs.

**Comment by bls1999** [comment]
The only reason I didn't suggest prepared statements is that I have absolutely no idea how to use them besides what's outlined in [this tutorial](https://www.w3schools.com/php/php_mysql_prepared_statements.asp).

**Comment by bls1999** [comment]
@aaaaaa123456789 thanks for that link; I'll read a bit more on the subject.

**Comment by aaaaaa123456789** [comment]
Do note that the link above uses the OOP interface. You can use OOP or procedural; there is no effect in security and virtually none in performance, it's ultimately a matter of style preference. The equivalent procedural functions are easily found in the PHP documentation (`mysqli_prepare()` is such a function).

**Comment by bls1999** [comment]
Gotcha. I think the biggest thing I'm confused about, to begin with, is why is saving a query to be executed at a later time more secure than executing it then?  I'm reading this documentation but not finding an answer.  Does `mysqli_prepare`, for instance, have some kind of escape function built-in?

**Comment by aaaaaa123456789** [comment]
It's basically a matter of parsing.

Consider the traditional example of SQL injection:

```sql
SELECT uid FROM users WHERE username = '$user' AND password = '$pass' LIMIT 1
```

I'm sure you know how that can be broken — you have to pass a string that breaks out of the string quotes. Escaping helps solve this issue, but as I said above, escaping is a fragile mechanism.

Now consider the prepared version of that query:

```sql
SELECT uid FROM users WHERE username = ? AND password = ? LIMIT 1
```

Note that binding arguments doesn't do a string replacement. The prepared statement is parsed (and compiled, at least in part) on its own, and it knows that it encountered two `?` marks, meaning that two parameters are required. The key point is that the `?` represent parameters, and thus cannot be broken out of — there is no escaping when you bind the parameters, because the engine knows to treat them as string values, not as SQL code. Since the `?` placeholders cannot represent code, it's impossible to inject any SQL in them.

**Comment by aaaaaa123456789** [comment]
To put it in simple terms that show what's going on, consider what the equivalent in PHP would be.

Imagine you had a `log_in()` function. Of course, you'd want to call it somewhere in your code in order to let the user log in. Let's assume that you're just taking the user and pass from the query string (it's a simple example), meaning that they would be in `$_GET['user']` and `$_GET['pass']`. In order to execute the function, you could do:

```php
$user = $_GET['user'];
$pass = $_GET['pass'];
$login = null;
eval('$login = log_in(array("username" => "' . $user . '", "password" => "' . $pass . '"));');
```

Of course, you'd notice that it's easy to break this, so you'd eventually do stuff like `$user = addslashes($_GET['user']);`. But this is rather obvious monkeypatching that doesn't solve the bottom issue, right?

**This is exactly what you're doing with your SQL queries.**

And that's the issue. You're concatenating strings to form executable code, in a way that is just as unsafe as the PHP code above. Prepared strings are essentially similar to functions in this regard. If you used a wrapper function in the code above, as follows:

```php
function do_login ($username, $password) {
  return log_in(array('username' => $username, 'password' => $password));
}

$user = $_GET['user'];
$pass = $_GET['pass'];
$login = do_login($user, $pass);
```

...then you'd have no issues whatsoever with PHP injection. SQL injection is no different.

**Comment by bls1999** [comment]
Okay, I think I got it from the first response.  So basically what's happening is you're telling MySQL not to take the text values you're getting at face value; you're telling MySQL to convert it from a string to parsed code in order to avoid injections. Right?

**Comment by aaaaaa123456789** [comment]
Pretty much the other way around: you're telling MySQL to NOT treat the
values as code. Just like parameters to a function (which are always pure
values, not code).

**Comment by bls1999** [comment]
So values passed to functions aren't treated as strings?  That might sound really stupid, lol.

**Comment by aaaaaa123456789** [comment]
???

Values passed to functions are treated as strings. They are NOT executed as
code.

Same with values passed to prepared statements.

**Comment by bls1999** [comment]
So if I'm understanding this correctly (I'm probably not), would this work to retrieve data from the db?

```
<?php

// connect
$db = new DB();

// prepare and bind
$stmt = $conn->prepare("SELECT * FROM users WHERE user_name = ?");
$stmt->bind_param("user_name", $name);

// fill in the blanks
$name = $_POST['username'];

// execute
$stmt->execute();

// close connections
$stmt->close();
$db->close();

?>
```

**Comment by aaaaaa123456789** [comment]
That seems fine to me.

Do remember that `mysqli_stmt::bind_param()` takes _references_ as arguments, and thus it is ideal to limit the scope of the variables used as parameters. Enclosing each individual prepared statement in its own function is a simple way of achieving that (although there is no issue with performing minor tasks before and after; it's just not a good idea to use them as part of a 100-line-long function).

**Comment by jacob-grahn** [comment]
PHP's PDO class hash a simpler api for prepared statements, I think that will be the easiest way to go. 

As a quick test, I converted the `level_unpublish` stored prodecure into a prepared statement. The files are [here](https://github.com/jacob-grahn/platform-racing-2-server/blob/master/http_server/www/remove_level.php) and [here](https://github.com/jacob-grahn/platform-racing-2-server/blob/master/http_server/queries/levels/level_unpublish.php).

**Comment by aaaaaa123456789** [comment]
While that will work, all parameters are bound as strings, which is less than ideal. The better (i.e., strongly-typed, as opposdd to stringly-typed) way to implement that function is:

```php
function level_unpublish ($pdo, $level_ID) {
  $stmt = $pdo -> prepare('UPDATE pr2_levels SET live = 0, pass = NULL WHERE level_id = ?');
  $stmt -> bindValue(1, $level_ID, PDO::PARAM_INT);
  $stmt -> execute();
}```

**Comment by bls1999** [comment]
Since this is being handled with the PDO conversion, I'm going to go ahead and close this issue.
