### ISSUE TITLE
Pr2's server crashing uncontrollable

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#219]
Servers are crashing randomly, we may know the issue, but error logs tells all....

Also, probably need to figure out why Gerry's ddos is causing 502's.

**Comment by Jmarroqu** [comment]
I don't think the 502-504 gateway error is from him ddosing it but who knows. Ever since of the server reset I haven't disconnected and to prove that to see if the server were stable or not I left a macro going to see if it'd d/c and they haven't and it was 1:05 amthe server reset and it's now 11:24 am so no need for Jiggmin to fix anything in here :P.

**Comment by EternalUF** [comment]
I believe one of Jiggmin's commits has solved this issue.
