### ISSUE TITLE
[Request] Fred Server

### ISSUE THREAD

**Issue by bls1999** [jacob-grahn/platform-racing-2-server#239]
Hey @jacob-grahn, can you bring back the Fred server and set the guild ID to 183 so the PR2 Staff can have their own server for testing and whatnot?

EDIT: Basically, the PR2 Staff team would like to have a server dedicated to testing/staff purposes. It doesn't have to be Fred; it could be Isabel or a completely separate server called PR2 Staff.

**Comment by Jmarroqu** [comment]
aw but I would love to go into Fred Server that was my favorite server before it was taken out ;c

**Comment by LP-PR2** [comment]
Isn't Isabel the new test server?

**Comment by woodenstix** [comment]
Who even plays on isisabel, lp is right

**Comment by bls1999** [comment]
Basically, the PR2 Staff team would like to have a server dedicated to testing/staff purposes.  It doesn't have to be Fred; it could be Isabel or a completely separate server called PR2 Staff.

**Comment by LP-PR2** [comment]
Why should the staff have a private server when regular members have to pay for them? If you want a private testing server, buy one like the rest of us.

**Comment by bls1999** [comment]
It would be useful for us since 1) we're working on code for the game that has to do with changes to moderation procedures, and 2) we would use it for staff operations and meetings.  It's not uncommon for games to have testing servers for developers and staff members.

**Comment by LP-PR2** [comment]
Then you can continue working on the game with a server that you pay for yourself.

**Comment by fourst4r** [comment]
you have a discord server, a mod/admin chat, a guild pm service (for anyone in the PR2 Staff guild), AND you want a free private server?

i don't get it, why can't you just test on an empty public server?

**Comment by bls1999** [comment]
@fourst4r When we test changes on an open server, it may open the server to crashes. Then we get posts like #138 which accuse us of intentionally breaking servers, as well as triggering some happy hours on server restart.

At any rate, I'll wait for @jacob-grahn to weigh in.  Also, Jiggmin is the owner of the PR2 Staff guild, so we can't even buy a server without switching the guild ownership (which is not our place to do).

**Comment by Jmarroqu** [comment]
I don't know where I stand on this but I'll put my two cents onto this. The Staff has a Admin/Moderator room that's already private so they can do what they want in there and test any "Servers" problem. I don't think that they should have a free private server all year long so why not let Jiggmin to do these options that I thought of. 1) Let Jiggmin put a Fred Server back onto Platform Racing 2 and that could be your own testing server. 2) Jiggmin makes a Pr2 tool for only for Admin to lock any "public" servers (not Private Servers) and whatever they need to test something they can kick any macroers/players out and have a meeting there. 3) Jiggmin does put a Pr2 Staff Private Server but the players that are in that guild will have to buy each day or months that they want in order to test/have meetings on. I would think if he does any of these it'd be a good enough compromise for the Pr2 Community. If you guys have a better idea please comment below.

**Comment by woodenstix** [comment]
finally who gets it! @LP-PR2 

As I stated before, you, staff members, should have used my advice and kept getting private servers for free, yet you did nothing and you are begging again

Our lord and savior bls1999 guys!
