### ISSUE TITLE
Moderators Being Given 19 Hats.

### ISSUE THREAD

**Issue by LP-PR2** [jacob-grahn/platform-racing-2-server#247]
Posting this here because I know that if I post this on JV2, my thread will be deleted.

Its no secret that the admins have been abusing their powers to benefit themselves, with the countless amount of alts and cronies being made mod (bls for instance has an alt with 50 hats). However, giving every moderator 19 hats to "make them indistinguishable on the player list" is bullshit. The fact that their name already displays in a blue colour, and their profiles clearly state "moderator" isnt distinguishable enough? I mean i've never had an issue in telling who's mod or not by these factors.

**Comment by bls1999** [comment]
Hi @LP-PR2, thanks for voicing your concerns.  This thread would not have been closed on JV2 since it is a valid concern, although I might have asked you to post in Ask a Mod since this somewhat questions staff actions.

When it comes to the hats, I'll let @jacob-grahn weigh in, but I've said this before and I'll say it again: long before I was an admin, I was given 19 hats by python (and so was his alt `pything`). @EternalUF and I have adopted this practice of giving all permanent staff members 19 hats (unless they object):
 - To make _permanent_ moderators stand apart from trials and temps
 - As part of each staff member's perk of obtaining all parts

My account `bls' Test Account` shows 50 hats on the player popup.  I don't actually have any hats on that account; it's just 50 commas in the array.  The reason the artifact shows on the player window is that I set it before changing the part values on the account.  I haven't logged into it since then, so it still appears as the set hat.  That account is just that: a test account.  I use it for random things like that every now and then.  Sometimes I ban it, sometimes I add or remove certain parts from it.  It's part of testing changes to the admin tools.  @EternalUF has accounts he uses for testing, too.

As for the "countless amount of alts... being made mod", we have a strict admin policy that no admin will have more than 1 alt mod account.  This has been a practice since the dawn of PR2; Tony had `ASiIva93`, python has `pything`, Jiggmin had `Jacob` (until he demodded it), I have `bIs1999`, and @EternalUF has `EternaI`.  There's [a staff list](https://pr2hub.com/staff.php), on which you can see every modded account on PR2.  We don't have any secret mod accounts; that information is public and accessible.

For the "countless amount of... cronies being made mod", we choose our staff very carefully after rigorous testing.  For now, we have enough staff; I don't anticipate promoting any trial or permanent moderators in the near future.  If you have a specific complaint about a moderator, please reach out to an admin or that moderator directly.

I assure you that we always have explanations and reasoning for all of our actions.  Some of this will be confidential from time to time, but we'll be happy to share what is not.  If you have any more questions, feel free to reach out to me (or another member of the staff team) directly on discord (bls1999#8616) or PR2, or post on JV2.

-Ben

**Comment by Jmarroqu** [comment]
Here's a feedback that I want to tell you @bls1999 I agree with those points but the thing is you've to look at it as a Member point of view. You're a staff and always be one till you decided to retire. How would you feel seeing Platform Racing 2 Staff having more than 13 hats and we cant get it because its "Staff only" the only thing I agree that should be kept staff is your tools and decision that you want to "staff" Maybe this "practice" should end and either let the Members have some copies hats as well or just revert every staff hat back to what they've before the hat edits.

**Comment by woodenstix** [comment]
InTrOdUcInG tHe 14Th HaT

GeT oNe By BeInG bLs SlAvE tOdAy

**Comment by VipaPR2** [comment]
Oh, this reminded me of something. I'm still waiting for the GGP prize @bls1999.

**Comment by bls1999** [comment]
Messaged you on discord @Vipa-PR2

**Comment by Jmarroqu** [comment]
Is there any solution for this thread? I'd think the staff maybe can let the Member(s) can get only 1 extra hat (which can be any) but only limit to 1 that way if "staff" can still have their "19" or "50" hats Not sure where @bls1999 @jacob-grahn stand on this..

**Comment by jacob-grahn** [comment]
It would be cool if there was a way to win a 14th hat without needing to be a mod. I'm open to suggestions.

**Comment by EternalUF** [comment]
I mean, it could open up more prize opportunities for contests.. the same ole bubble set, reindeer set etc is getting stale among the community when it comes to prizes for contests. This could definitely spice things up a bit. But I feel it should be even harder to obtain than an artifact hat. 

On a flip side, we’d only be able to award a blank hat, and it gets annoying explaining to new or old returning members that the 14th hat isn’t a hat at all rather than a blank, hat count boosting slot :P
