### ISSUE TITLE
Petition

### ISSUE THREAD

**Issue by LP-PR2** [jacob-grahn/platform-racing-2-server#270]
https://www.change.org/p/jiggmin-jacob-grahn-unban-the-pr2-botters-we-didn-t-break-any-rules

Sign if you agree.

@jacob-grahn

**Comment by bls1999** [comment]
"I want to make it clear that this thread can in no way cover all possible rules and issues the PR2 staff may discipline users for."

**Comment by LP-PR2** [comment]
@bls1999 if botting has been known about, why is it not listed?

**Comment by bls1999** [comment]
It falls under the first rule on the list.

"1) No Cheating, or encouraging/teaching others how to cheat.

This is the big one. Cheating is defined on PR2 as using any third-party program that gives you an unfair advantage over other players. This includes (but is not limited to) hacking."

**Comment by LP-PR2** [comment]
@bls1999 that include macro recorders too right?

**Comment by Jmarroqu** [comment]
@jacob-grahn What's the big deal of "botting" when Pr2 is gonna go down in 2020? Not like this will matter and if you want you can even change the exp system in PRF if you're afraid that the accounts transfer from PR2 to PRF login will make a "big deal". Also, if mouse recording/macro was "cheating" and it goes to the first two rules then that goes the same as botting and all first offensive should get banned for 1 month since it's "hacking/cheating giving unfair gains" if this was true.

**Comment by woodenstix** [comment]
BOTTING DOESNT EDIT THE CODE

CHEATING DOES

BLS YOURE SO EDUCATED
