### ISSUE TITLE
Simming, Macroing, Botting.. What's the difference when it comes to "Cheating"?

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#293]
Everything that happened when the game got created and has been added now there's a lot of things that can be consider "cheating" the word is when typed on google; http://prntscr.com/iurppi or on bing; http://prntscr.com/iurqa0 In platform racing 2 it seems like the rule "cheating" is just vague definition and has no explanation. For example; Player(s) who uses a higher stats than a player who's the same level/rank could consider cheating to the other player since they don't got enough stats and it isn't fair for them that they're at that level/rank. "Cheating" can be anything on Pr2 that can cause one or more person(s) to feel like they couldn't achieve or do the same because either they have better stats, using glitch stats, using items to get out of maps instead of following the path that the creator of the map are trying to lead them to.  I think before the Pr2 Staff do more hasty bans I think they need to fix and define "cheating" more and within all the bans that happened from the past to now (3/22/2018) to get un-ban for this foolish "rule" that isn't 100% clear and give the players an apology for their wrongful unclear ban that they did to us. @jacob-grahn Please write us a responds ASAP, thank you.

Simming is cheating cause you can get some unfair exp from normal players that aren't simming and the most that can sorta replicate simming is "racers" when they use glitches/fast stats to beat the maps

Macroing is cheating because you can use a Mouse Recording Program or Script to macro 24/7 which is a 3rd party program which is against the rules

Botting is cheating because you can use a 3rd party program to get some insane amount of exp within seconds unlike Macroing but a level higher.

Yet the only reason the staff have given us is "botting is hacking", "botting is cheating", "use of 3rd party programs

The rules currently contradict themselves, I can give multiple cases of hacking and cheating which is all classified as ok (antohns customized pr2 theme, bls's level finder tool that uses a 3rd party program, about any glitch which allows you to beat a map faster than going the intended route)
Yet you choose to ban multiple people over something that wasnt causing a major issue, was due to be fixed the next day and was not more beneficial than macroing.. the exp gains were actually worse than macroing

We want a definitive public answer from @jacob-grahn, as we aren't getting anything from any of the other admins.. since you allowed macroing which is using a "3rd party program" "script" "hacking" "cheating" so please give us your final feedback without no "close doors" with the staff and make a public statement for the whole PR2 Community can know your answer.

**Comment by LP-PR2** [comment]
@jacob-grahn

**Comment by LP-PR2** [comment]
"threads that can be closed"

Exactly our point @jacob-grahn

**Comment by bls1999** [comment]
The PR2 Staff will review the cheating rule and make changes as we see fit. Stay tuned.

**Comment by LP-PR2** [comment]
@bls1999 we're not asking for your input, you haven't given us any answers when we wanted them from you, so we don't have any faith in you. 

@jacob-grahn

**Comment by bls1999** [comment]
@LP-PR2 as long as I'm an admin, I will continue to answer your questions as that is my job.

**Comment by LP-PR2** [comment]
@bls1999 then answer the question

**Comment by bls1999** [comment]
@LP-PR2 I just did. The PR2 Staff will review the cheating rule and make changes as we see fit. Stay tuned.

**Comment by LP-PR2** [comment]
Because so far, every single pr2 staff member has avoided these exact questions in this thread, we have no definitive and we're sure that we're not going to get one. Which is why we want @jacob-grahn 's definitive input and not a biased bls bandwagon input

**Comment by bls1999** [comment]
@LP-PR2 We work and develop rules as a staff team. Amendments to the rules require input from all members of the team, which takes time. We are working to get the answers to you, but we ask that you remain patient while the process is ongoing.

**Comment by LP-PR2** [comment]
@bls1999 if you make me wait 16 days for a decision, i promise you that i won't be logging in again.

**Comment by bls1999** [comment]
@LP-PR2 Try to be patient. We'll do our best to get you an answer before your ban expires.

**Comment by Jmarroqu** [comment]
@bls1999 Seems like you're afraid to let Jiggmin to put his input.. Wonder if you know that he won't side with you again just like how he rekt all of your "Macro" ban. We don't want staff answer all we ask is for @jacob-grahn to give his input since creator of game beats Staff decision.

**Comment by a7x3** [comment]
@Jmarroqu @LP-PR2 

You either wait, or you leave, bevause trust me, if you want a reply from Jiggmin about these matters, it's going to take a lot longer than what it is already. Enough of this, just wait.

**Comment by bls1999** [comment]
> Seems like you're afraid to let Jiggmin to put his input..

:thinking:

Jiggmin can say whatever he wants, but one of the reasons we have a staff team is to delegate decisions like this to people other than Jiggmin.  I'm doing my job by answering your questions, and I'll continue to do so as long as I hold this position.

**Comment by Jmarroqu** [comment]
Correction, you only got that position because you sucked on Jiggmin's wife in freegoose to get it since you made yourself a "fan" and "caring about the pr2 community" but I got nothing but time so I don't care how long I have to wait @a7x3 and any Staff (no matter what game) job is to follow/enforce the rules that the creator set on the game. You can't edit the rules to your choosing just because a creator isn't active it isn't your game so no need for it. Anyways, "Jiggmin can say whatever he wants" just shows how you don't know what you're doing as the "Head Admin". This game was active with 4+ servers with over 200 players till the game died out because of the "enforcing" of the rules that you guys were changing without the knowledge or public inputs on the Pr2 community.. if you guys at least include the Community instead of hiding in a private room and include our voices the game wouldn't have died out. Of course, in my opinion.

**Comment by a7x3** [comment]
**Anyways, "Jiggmin can say whatever he wants" just shows how you don't know what you're doing as the "Head Admin"**. 

I'm sorry what, what has him being admin got to do with Jiggmin being able to do what he wants, which IS true...

**Comment by bls1999** [comment]
Let the record show that the original language used in that message was this:

> Correction, you only got that position because you sucked on Jiggmin's wife in freegoose to get it

**Comment by LP-PR2** [comment]
@a7x3 great professionalism telling us to leave. I'd expect more from a mod.

**Comment by LP-PR2** [comment]
How about @bls1999 and @a7x3 stop replying to us here with pointless arguments and start discussing the OP.. because i'm still waiting for an answer.

**Comment by EternalUF** [comment]
I’ll but in on this since this is getting ridiculous. Your only agreement is basically “the game is going to die, so who cares about the rules” which is completely nonsense in my opinion. If that was the case Jiggmin wouldn’t have promoted two Admins to do a job. So continue on, yes people have donated money, only about $40 though. Any who, you talked about adding new parts and whatnot, but if you’d actually been paying attention you’d know that, that is all impossible currently since the source code to Pr2 is lost. We’ve said this HUNDREDS OF TIMES. The money received from Jiggmin2 donations are purely there to keep the site running (domain hosting, and the initial funds we put in) There isn’t a funding issue currently, in my opinion. You mentioned to use our streaming base to get new players, Bls and I both stream, but you have to realize our bases are only like 10-20 followers and 99% of which are already Pr2 players. So that’s also an invalid arguement. We can’t put ads around for Pr2, Jiggmin would need to do that. (Already tried) also promoting Pr2 with Kong, we’ve already tried. Some stuff with the Kong API is broken in the client (which can’t be fixed) so we are at a dead end there. You have the wrong perception on staff which I believe is scewed by previous decisions that weren’t in your favor. Over the past month or so, Pr2 has seem numerous updates which is beneficial to all.

**Comment by a7x3** [comment]
@LP-PR2 I'm not here to be a professional, I'm a mod to help keep the game away from players like yourself.

**Comment by Jmarroqu** [comment]
Where did you read that off when you got promoted? I think once you're a temp mod-moderator you've to read the rules and they never said anything like that 🤔 @a7x3

**Comment by Jmarroqu** [comment]
Kong isn't a place to put your ads did you not know that Gamestop is dying around the world and if you didn't know they run that website @EternalUF

**Comment by Jmarroqu** [comment]
Actually, Jiggmin can make new codes to add things to Pr2 like he did with the current "Hat and Campaign Bonus" so stop playing stupid @EternalUF

**Comment by Jmarroqu** [comment]
Like @LP-PR2 said instead of hiding and running from the OP questions just answer it and we're done but you haven't since you guys don't have no clues/just making shit as the days go on.

**Comment by Jmarroqu** [comment]
A7x3: I'm a Pr2 staff and don't need to be "professional, nice, follow the rules" how are you a staff? Yet again how does a game that has less than legit 10-15 players needs so many staff at most 1 admin and 2 moderator can do the trick for the amount of players that Derron gets.

**Comment by Jmarroqu** [comment]
You know how easy you can put your ad on Steam for flash games? @bls1999  @EternalUF just email and ask and make a trailer that's all. I can easily put up the last remaining years of ddos protection for Pr2 because I as a fellow Pr2 player care about the game but of course the staff are "busy" "waiting for jiggmin" "changes rules to fit them to their way of staffing" The only reason why the Community is against Pr2 staff because the Staff haven't done ANYTHING to make us support their decision and that's 100% fact.

**Comment by bls1999** [comment]
@Jmarroqu

It's not our job to advertise the game.  It's our job to oversee member behavior and operations.  If Jiggmin wants to advertise it, that's his prerogative.

Kong still has thousands of activate members and it's an easy place to advertise.  PR2 was easily one of the biggest games ever on Kong.

How about actually learning about what you're talking about before accusing someone of playing dumb?  The client code is lost.  We can't make changes to the client.  That includes in-game elements such as parts, GUI elements, etc.  The Hat/Campaign bonus is a server-side change.  You can see that in multiplayer-server/rooms/Game.php.

Just because you guys don't like the answer, doesn't mean we haven't answered.  Your answer (for the third time!): The PR2 Staff will review the cheating rule and make changes as we see fit. Stay tuned.

I encourage anyone in the PR2 community to come to us with constructive feedback on our performance.  We take the concerns of the community very seriously; However, when we get things like "the Staff haven't done ANYTHING to make us support their decision and that's 100% fact" and "you guys don't have no clues/just making shit as the days go on" and "you only got that position because you sucked on Jiggmin's wife in freegoose to get it" without any intellectual merit or constructive feedback attached, you can't possibly expect us to take you seriously.

Blaming us for the inactivity of PR2 is an action that is laughably ignorant and short-sighted.

And finally, I challenge you to adhere to these rules when attempting to form an argument: https://owl.english.purdue.edu/owl/resource/659/03/

**Comment by Jmarroqu** [comment]
You know how easily Pr2 can change if the staff will stop their attitudes towards the community? 
-> "Staff can't learn any language only English only" Why? This is 2018 where we're welcome to speak with any language as long as that LANGUAGE isn't breaking the rules (which I 100% agree) Solution: Have Mix Staff instead of "English only" Staff problem solve. 

-> People are spamming/flooding and it's annoying Solution: if someone says A (hit enter and do it again) instead of showing up just do "A (10)" that way it won't flood the chat and it will show how many times they're doing it but it'll stick to ONE line.  

-> People who Nuke, Solution: make sure even if they tried you can only do a certain amount of ()()()()()() between a word or in total so you don't get those long message

-> Filter I get the game was intended for kids/still is but you can't say that those "bad/rude" words actually means what they are in today worlds. The word "Fuck" wasn't used like how it was it meant something different AGES ago (research all the root "bad words" if u don't believe) Solution: you say Fuck "F*** You B****" would probably work than to get warned/banned for filtering like jfc. 

-> Inappropriate levels or names/Hacking/Cheating/, Solution: Allow members to report them instead of you guys finding out too late like /report [username] for [Reason options] [Inappropriate levels] [Hacking: Cheat engine, item hacking, etc] [Cheating] 

There's a lot of the rules that can be easily fixed if you guys tried to put in your effort

@bls1999 I saw your comment so gonna post my thoughts about that in here too

Jiggmin can mod the client to put in a new source code 😕 .. or I would think he can make another one and make it work with Pr2. Making fun of the way I type isn't an issue with me because that isn't everything important in the real world or even online games. You can or can't take me serious but not when you've a lot of players that do agree with these topics

**Comment by bls1999** [comment]
"You know how easily PR2 can change if the staff will stop their attitudes towards the community?" is like saying "You know how much crime will go down if police stop enforcing the law?"

The English only rule has been one forever.  The game is in English.  Some staff members speak different languages (i.e. TRUC speaks French), but if an English-speaking unilingual mod is met with chatter they don't understand, it's their right to tell the people to speak English.  We'll promote new mods if there is a need for them, not because we want a Spanish speaker on staff.

The spamming/flooding fix you suggested would require a client edit.

The nuking fix is intriguing and could possibly work.  I'll look into that at some point.

The filter is not going away.  Likewise, the filter evasion rules are not going away.

I'm going to try to add a /report function for all chat reports like there is on PR3.  Reporting a video of the race would require a client edit.

Jiggmin cannot mod the client to "put in a new source code."  He's not interested in making a whole other client just to fix a few things.

I'm not making fun of the way you type; I'm commenting on the absolute irrationality of the majority of your arguments.

**Comment by a7x3** [comment]
**A7x3: I'm a Pr2 staff and don't need to be "professional, nice, follow the rules" how are you a staff? Yet again how does a game that has less than legit 10-15 players needs so many staff at most 1 admin and 2 moderator can do the trick for the amount of players that Derron gets.**

We've manage to keep people who act like yourself off the game, THATS why I'm staff.

**Comment by jacob-grahn** [comment]
Using the +5 exp exploit in secret for an extended period of time was cheating, regardless of the method used. Now that the exploit is patched, there may or may not be a need to continue the botting ban. That remains to be seen!
