### ISSUE TITLE
?

### ISSUE THREAD

**Issue by LP-PR2** [jacob-grahn/platform-racing-2-server#319]
http://pr2hub.com/bans/show_record.php?ban_id=94773

**Comment by LP-PR2** [comment]
https://www.youtube.com/watch?v=JXeaWap17Mg&feature=youtu.be

**Comment by Jmarroqu** [comment]
You posted a ban id and youtube but what's the point of posting this? Let me guess, This person hacked the game and got unban by the person who banned them and you want to know that if Jiggmin or Bls1999 can do the same?

**Comment by LP-PR2** [comment]
@jmarroqu just curious, i mean if his ban can get lifted early.. ours can too right? Or is that favourtism?

**Comment by Jmarroqu** [comment]
@LP-PR2 It wouldn't surprise me if the staff has favourtism on the game. Question is, @jacob-grahn are you going to allow this and if so can we get the same treatment?

**Comment by bls1999** [comment]
That video is from more than a year before the ban happened.  It is not related in any way.

Astro's case was a special one, and not as clear-cut as yours.  I'm not going to get into specifics, but he shouldn't have been banned for that long in the first place for what he did.  I lifted it for "good behavior" because he was polite and articulate in his appeal, as well as explaining how to prevent what he did from happening again.  You have complained on multiple GitHub threads, while Jiggmin has specifically said that this isn't the place for those types of discussions.  You have been nothing but rude to my staff and me on Discord and in general.  There's absolutely no reason for me, or any of my staff, to lift your bans for "good behavior" because there frankly has been no example of this since you both got banned.

**Comment by LP-PR2** [comment]
@bls1999 "it is not related in any way"
You wouldn't ban him until i showed you the video, you seem to forget that it was my report on which you banned him by. Do i have to go digging for the logs to remind you? Or are you capable of doing that?

There was nothing "special" about the ban, the video showcased a user cheating in plain sight, self recorded and uploaded, witnessed and overlooked by the entire community except those who can clearly see through his bullshit. He cheated. There's no "getting into specifics", it's right there in plain evidence as documented in HIS video.

My complains have merely been a statement of how trash of an admin you really are. With your double standard rules, personality, and if i'm honesty, i think you have something against the people that you banned including myself. I'm not sure why, considering your staff came to me when the rule list was being put together and asked me for my suggestions, which I willingly put forward. I was the one who recommended that you made a rule thread and YOU didn't even do that, another mod took the time to write it up themself, but you'll take credit for that too won't you?

The only good things you have actually done for this community is patching little things here on there on github and maybe an account recovery along the way. Other than that, you've really done nothing special that actually warrants you being an admin.

**Comment by bls1999** [comment]
Yet another example of you being rude to my staff and me.  Serve your ban.

**Comment by Jmarroqu** [comment]
Being rude outside of Platform Racing 2 shouldn't be consideration of getting yourself unban. You can't ban for outside Pr2 so why should our actions be any different? @bls1999

**Comment by LP-PR2** [comment]
@bls1999 so you're not going to comment on anything else that I said? 

P R O F E S S I O N A L I S M

**Comment by libido9000** [comment]
**Astro's case was a special one, and not as clear-cut as yours.** 

His case is obviously much worse than mine, as there is no proof of me hacking except my confession and Wolfie’s testimony. You guys are calling that ”clear-cut”, but here we have a video of someone clearly hacking and it is apparently not as ”clear-cut”? 

**I'm not going to get into specifics, but he shouldn't have been banned for that long in the first place for what he did.**

What he did was even worse than what I did. Sure, we both hacked sure, but he put actual time and planning into his hacking and showcased it freely whereas I did it for a few seconds

**I lifted it for "good behavior" because he was polite and articulate in his appeal, as well as explaining how to prevent what he did from happening again.**

This is a load of bullshit, as I submitted an appeal of myself confessing and being as polite as I could but got nothing but shit on by the moderator who banned me. Why didn’t my ban get lifted for good behavior then?

**You have complained on multiple GitHub threads, while Jiggmin has specifically said that this isn't the place for those types of discussions. You have been nothing but rude to my staff and me on Discord and in general.**

If your staff team provides bad support and is outright rude to us by mocking us, what reaction are you expecting to get? If he doesn’t deserve to be banned for 22 days even, what did I do that was worse?

-Saurus

**Comment by Jmarroqu** [comment]
This is why I don't like the "AAM" to be private, it should be public, but only have the Pr2 game staff/website staff be the only ones to reply to the appeal while we have public people to view it to make sure that the Staff and Player of the appeal are both being handle fairly.  @libido9000

@bls1999 Let me first and say I don't hate you nor your fellow staff. But as a Pr2 player since 2009 I've seen many things with the "Platform Racing 2 Staff" I know every fellow player that became staff has their own opinions of the "Rules" which I respect but when a Admin (You, Bls1999) doesn't allow their staff to voice their decision and tells them "This is how it's going to be" how is that even a _**fair **_ way to do things as the leader of your Staff? Also, I'm not sure why we're saying your staff, when in fact it's Jiggmin Staff and you don't have the right to _**own**_ unless you're a dictatorship admin? 

@jacob-grahn please look at this screenshot, http://prntscr.com/ix56f4 or read this quote by your "Head Admin " bls1999 - 03/08/2018 Hey @Colind when the update gets pushed to the other servers, can you test your bot there to make sure it doesn't work" I responded and put my input if I was known that it was a trap I wouldn't have said anything since he had nothing but the fact that this was _**On the date that it was getting patched.. why are we receiving a ban of an exploit that was going to be patch anyway?**_ Once again, I don't mean to be "Rude" to your Staff but when having problems in a game that you're not active which I am not blaming you since you've more important things to deal with like your job, wife, making PRF (hopefully) and etc I just want you to know that you shouldn't always believe your staff over the Pr2 Community when without PLAYERS you wouldn't have a _**Game Staff for Platform Racing 2**_. 

- Colind

**Comment by bls1999** [comment]
The fact of the matter is that I made a decision based on the information I had at the time.  Additionally, this was before the rules were even written.  Was it maybe not the best thing to do?  Possibly.  Now that we have guidelines for how long to ban set in the rules thread, this would never happen again.

**Comment by libido9000** [comment]
Why did you try to justify it then? You only bothered to admit it was wrong when I countered your excuses by bringing up my ban. Why didn’t you just admit it in the first place? As this stands now it is quite unfair that people have been acquitted prematurely and that you actually defended this.
