### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Jmarroqu** [jacob-grahn/platform-racing-2-server#352]
A lot of the staff thinks that since Jiggmin lost the source code there isn't a way to be able to go around it.. but there's so I am not sure if maybe @jacob-grahn you're not aware that anyone and you can do this method that I came across when researching. You can use this program called Hex Ray's interactive disassembler or Ida.

In this video; https://www.youtube.com/watch?v=A9U5wK_boYM this guy deeply explain that he doesn't have the source code for GH3 on PC and fixing bugs without the source code. I am assuming that Jiggmin does this as well for Platform Racing 2 he can still do the changes/edits to the game without the source code. 

I know this issue isn't suppose to be here so I am sorry but my intention is good :)

**Comment by isokissa3** [comment]
Using hex editor would be pain in the ass, instead using programs like JPEXS to edit the source in ABC (ActionScript Bytecode) is possible. Fixing small bugs is simple enought but when you want to start adding classes and new UI elements its becomes tidious. 

Adding new classes is pretty simple, I haven’t done it with JPEXS but its at least possible with RABCDAsm

Adding new UI elements requires for you to import them to the SWF, I have used JPEXS for this as its pretty straight forward. Then you need to edit the XML file (or create new one) that specifies where the UI elements are. After that you need to create class(es) related to the imported asset(s) in order to be able to reference in the code. The process takes at least 5mins to create new UI element even if you know what you are doing. Creating script to do the work for you is required for bigger changes.

The most fun part starts when you learn ABC :) Sadly I barely even remember it and how you had to edit different values when you started to doing bigger changes to the code base.

I have once added few UI elements to heavily obfuscated SWF. I even added new functionality but yeah, lets not talk about that. I dont really recommend for anyone if they dont want to jump in to the sinking ship.

TL;TR: Possible, inpractical, needs experience to get the job done fast

JPEXS Flash Decompiler: https://www.free-decompiler.com/flash/
ABC [Dis-]Assembler https://github.com/CyberShadow/RABCDAsm

**Comment by jacob-grahn** [comment]
It was [secureSWF](url)

Obfuscation is fairly pointless, but sadly I learned that lesson to late.

**Comment by bls1999** [comment]
@BrokenBulb78 The method you used still has blocks of heavily obfuscated code.

**Comment by Jmarroqu** [comment]
Anyways, just wanted to put my input and I did so going to close this and thanks for the replies.

**Comment by bls1999** [comment]
Sure thing, @Jmarroqu. I wish we could do that stuff, but it looks like we won't be able to do so anytime soon. :/
