### ISSUE TITLE
Issue with spectator mode

### ISSUE THREAD

**Issue by BrokenBulb78** [jacob-grahn/platform-racing-2-server#372]
It's just me or has anyone noticed that? When I'm on a level, the players are running smooth, but when I click quit and enter the spectator mode, the players are lagging too much and they're teleporting every 1 second. @jacob-grahn

**Comment by Jmarroqu** [comment]
Ever since Jiggmin said when you're able to quit and see the other players "play" but clicking the map and a spot you wanna see that also doesn't work :/

**Comment by bls1999** [comment]
The other players' positions are updated in real-time when you're right next to them in the level, but when you're far away, they update at 1-second intervals.  When you forfeit in a level, your character fades out but doesn't go away; it actually stays in the same place as an invisible sprite (as seen [here](https://youtu.be/zJIrUBamLEs)).  Since your character stays there and the game thinks your camera is where your character is, if the other players are outside a certain radius of your character, they'll end up updating at 1-second intervals while you're trying to spectate.

I hope I explained that well enough.  As for a fix, I'm not sure if this code is in the client or the server. @jacob-grahn?

**Comment by BrokenBulb78** [comment]
Oh I see @bls1999

**Comment by bls1999** [comment]
Upon further inspection, I think it's very possible that the code could be modified to lock the player to the camera after forfeiting.  That being said, I have no idea how that would be done.  @jacob-grahn?

**Comment by LP-PR2** [comment]
Great idea @bls1999.. let's just screw over every contest that relies on a spectating feature because it's a little laggy.

**Comment by bls1999** [comment]
I'll get this done in a future update. @BrokenBulb78

**Comment by bls1999** [comment]
Fixed in v156'
