### ISSUE TITLE
IP Admin Search

### ISSUE THREAD

**Issue by EternalPR2** [jacob-grahn/platform-racing-2-server#387]
The Admin IP search tool crashes everything..... Sorry..........

**Comment by bls1999** [comment]
LOL, that's what's wrong! :joy:

**Comment by woodenstix** [comment]
i wonder how long until my ip gets leaked

**Comment by bls1999** [comment]
@jacob-grahn could you send me the error log for `ip_deep_search.php`?  I'm hoping to get to the bottom of why this being so weird.

**Comment by jacob-grahn** [comment]
I looks like one of the queries takes a few hours to run, and that creates an ever growing backlog of requests that eventually overloads the server.

**Comment by bls1999** [comment]
Oh, joy. I'm thinking that the db just can't handle the request?  I know there are a TON of rows in `recent_logins`, as they've been there literally since about June 1, 2013. These are extremely useful to us in verifying account ownership, so obviously clearing out that table would do more harm than good.

Anyone have any ideas? @jacob-grahn @aaaaaa123456789?

**Comment by aaaaaa123456789** [comment]
Which query is causing the problem?

**Comment by jacob-grahn** [comment]
We should probably delete recent_logins older than a month with a cron.

**Comment by aaaaaa123456789** [comment]
This sounds like a bad query plan to me (something doing a nested full table scan), which can probably be solved in a better way. That's why I asked about the query.

**Comment by bls1999** [comment]
@jacob-grahn we actively use the entries in recent_logins for account verification. Additionally, clearing out the table would defeat the purpose of the admin IP search.

@aaaaaa123456789 https://github.com/jacob-grahn/platform-racing-2-server/blob/master/http_server/queries/staff/admin/users_select_by_ip_expanded.php

**Comment by bls1999** [comment]
@aaaaaa123456789 

On `users`:
```mysql
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `name` (`name`) USING BTREE,
  KEY `guild` (`guild`)
```

Nothing on `recent_logins`

**Comment by aaaaaa123456789** [comment]
You'll want to create an index on user_id for recent_logins.

**Comment by bls1999** [comment]
@aaaaaa123456789 sounds good, thanks. So @jacob-grahn, this:

```mysql
ALTER TABLE `recent_logins`
ADD INDEX(`user_id`);
```

**Comment by famelegend1** [comment]
so if i get this right, the problem is that you're running through thousands and thousands of accounts, some  with thousands of logins itself. 

i suggest you guys create a range from which to search from. For example, you could search in a max range of 100 most recent logins, entries 100-200 in the database specifically,   etc. this should relieve stress on db

**Comment by bls1999** [comment]
@famelegend1 @aaaaaa123456789's fix should work.

**Comment by jacob-grahn** [comment]
I'll be honest, I still think we should delete login ips older than a month. Not for performance reasons, more for privacy reasons. It was never my intention to record every login ever, which is why the table is called `recent_logins`... I apparently just forgot to ever set up a cron to delete them.

I understand that this will make it harder help with account recoveries, but I wonder if it's worth it to help users recover stolen accounts in the first place. Most of the stolen account cases boil down to people sharing passwords with each other.

**Comment by EternalUF** [comment]
> The answer used to be universally 'no', and I'm still not sure of when or why this changed

The answer still is typically no, we don’t recover stolen account due to scamming, account sharing, and anything else along those lines. The disclaimer that the security of your account is no one other than your own is explicitly stated in the Pr2 Rules list.

98% of the account recovered through AAM are accounts that have not been logged in since 2014 or earlier, which brings me to my next point. Those login records that date back to those times aid significant in confirming registration location when an account is trying to be recovered. 

Honestly speaking, the Admin IP search tool would be EXTREMELY beneficial, but I believe we could survive without it’s existence if there is to much of an issue query wise. The mod IP search tool is already working wonders, and we are grateful to have this tool in aiding investigations.

**Comment by bls1999** [comment]
The privacy factor is a good point, but I feel obligated to point out that we can already see all of this information in the `player_deep_logins.php` script and the `player_deep_info.php` script.

I strongly believe that truncating the `recent_logins` table would be detrimental to our ability to recover old accounts for users who lost them.  We do our very best to allow users to reclaim their accounts that were lost simply to a forgotten password/email.  Our success rate is, more often than not, attributed to the fact that we can see all of the user's logins since about 2013.

I understand the dilemma you must have when mulling this idea over, and I'll respect the decision you make; However, I strongly urge you not to do so.  By truncating the table, it would make `player_deep_logins.php` and `ip_deep_search.php` useless and make our jobs a whole lot more difficult.

**Comment by famelegend1** [comment]
Positives:

- Recovering lost accounts (gives plentiful material to verify ownership from)
- Finding sketchy players/ban evaders
- Essentially an even more detailed mod IP search tool, which is already very useful
- Can link proxy logins together

Negatives:

- Privacy is a question mark
- The argument that an account should be the owner's sole responsibility
- Searches through a lot of items; has potential to disrupt server regardless
- Due to proxy logins, the admin IP search may or may not lead to false positives

there are good arguments to both of this, and i've laid out the pros and cons to this situation to help you guys in making a decision. If I've missed anything, tell me

**Comment by bls1999** [comment]
@famelegend1 Regarding the negatives:
 - Privacy is only a question mark with faulty security. We've patched all of the known security loopholes in the server code (only getting stronger with #484) and beefed up our staff verification and account security within the team.
 - While we do have a regular policy that the account is the owner's responsibility, we recover accounts for users who lost them due to a forgotten password (not scamming/selling, etc) because we're able to do so. It has a very big nostalgia factor for users when they finally get access to an old account again.
 - With the column index on `user_id` in `recent_logins`, that shouldn't be a problem.
 - While we do sometimes make mistakes when banning a proxy IP for b/e, that's part of the reason why users are welcome (and encouraged) to appeal their ban in Ask a Mod if they feel that it was a wrongful ban.  I know I've made my fair share of mistakes in this department, but the `recent_logins` table was a resource that greatly helped us in determining that SZR was impersonating Shadow Z, Firefight, and Intrepid.

**Comment by FearlessFlare** [comment]
No one impersonated anyone though. This is all your imagination and part of your vendetta against people who are simply able to do stuff that you can't do at the moment. You're going to have to accept that, I can't help someone like you with that.

**Comment by aaaaaa123456789** [comment]
Huh? Did you leave your reading comprehension skills at home? I've been helping out here...

**Comment by famelegend1** [comment]
@FearlessFlare well i added the real intrepid on discord, so you're going to have to accept that. i can't help someone like you (if you're even a person at all, you might as well be an "it") with that.

**Comment by bls1999** [comment]
@FearlessFlare said:

> No one impersonated anyone though. This is all your imagination and part of your vendetta against people who are simply able to do stuff that you can't do at the moment. You're going to have to accept that, I can't help someone like you with that.

Not really sure what you think you can do and I can't, but I'd love to hear that.

I'm really getting sick of the compulsive lying and the constant attempts to invalidate our response to your offenses. The IPs speak for themselves. Your act is not in the slightest bit believable.

Additionally, I find it VERY interesting that "Firefight" and "Intrepid" just so happened to COMPLETELY vanish immediately after  you were found out to be a liar and a crook. We also suddenly got two more requests from the [Real] Firefight/Intrepid to recover their accounts that they "knew were compromised for a while but didn't think to do anything about it."  Give. It. A. Rest.
