### ISSUE TITLE
Email concerning a possible security issue

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#42]
I also sent you an email yesterday (jacob@granh.io) pointing out a possible security issue that may be too sensitive to post on Github, could you check that for me! Thank you.

**Comment by jacob-grahn** [comment]
That login_code is from when I was playing whack-a-mole with people producing hacked clients. I would change the login_code stealthily without anyone noticing, and then a few versions later I'd ban anyone who tried to log in with the right client version, but the wrong code for that version. It would probably be good to just take that line out, since it's not used any more.
