### ISSUE TITLE
Banning issue

### ISSUE THREAD

**Issue by EternalUF** [jacob-grahn/platform-racing-2-server#72]
Bans are echoing disconnecting users when banned from the client, but when it runs server side this error message occurs: 
message=Error: Could not perform query.

**Comment by jacob-grahn** [comment]
Dangit this was hard to fix. When I transferred servers, I also moved everything over into an upgraded version of mysql. The old version of mysql would add a default timestamp of '0000-00-00 00:00:00' to the `modified_time` field. That value is invalid in the newer version of mysql though. It wouldn't let me update the table to get rid of the invalid values because... the table contained invalid values! I had to drop the table, manually edit the text file that contained the values, and then import it back in. Sheesh.
