### ISSUE TITLE
better macro anticheat(or wat)

### ISSUE THREAD

**Issue by woodenstix** [jacob-grahn/platform-racing-2-server#87]
there is no proof someone is macroing so please implement new ones because ppl getting banned from left to right

**Comment by jacob-grahn** [comment]
Right now I'm leaning towards removing macroing from the list of ban-able offences, rather than trying to get people to prove that they are human.

**Comment by FearsPR2** [comment]
@jacob-grahn Please do this. The remaining active playerbase are all simmers (me included) and I personally don't feel like using a simple mouse recorder is cheating at all; especially when you consider that there aren't very many racers left that still race actively. So the stat points aren't even going to good use anymore. I was recently banned for a full month for using a simple mouse recorder, and I just don't feel like that's warranted. Especially since this 1 month ban for "macroing" was my first offence of any kind.

**Comment by Jmarroqu** [comment]
@jacob-grahn Hello Jiggmin. This is Colind (for some reason someone took my username). I've been a long time fan of your game since 2010. Your game was a great way to get rid of my stress so I thank you for that. I haven't really macro since I got caught and banned since 2012 (?). I just don't understand why would you go against simmers/macroers when they in fact are giving you $ on VoM when buying Happy Hours, Private Servers, Rank tokens and etc. Anyways, I hope you can really lift this macro as a rule because your Admin (Bls1999) is just hunting down players that he can find and just banning them without doing any proper warnings/bans. In the past (Aaaaaa123456789) a ex moderator used to just d/c the players and shows it on the pr2hub.com/bans as a "macro test" and let you have time to login and either PM or talk to them but Bls is just stalking them going in and just banning if they don't talk. Tho I don't think that's a great way to ban players for macroing we don't need to and I was hoping for him to do it on me because I would record what he does and not talk and let him ban him and upload the video and show that I wasn't macroing but anyways in before a long rant I hope you can lift everyone macro ban ASAP Jiggmin. P.S. Keep up the good work and hopefully PRF will be a thing soon ;D

**Comment by bls1999** [comment]
Hi Colin, thanks for your feedback.

My macro tests usually consist of me finding the level in which the suspect user is entering and then asking for human verification three times.  Each message is accompanied with a warning that failure to reply will result in a macroing ban.  I don't enjoy doing that, but as a staff member it's my job to enforce the rules as they are outlined.

I hope Jiggmin gives us a concrete answer on this soon.  Personally, I don't think macroing should be allowed simply because you're using a third-party program to gain an unfair advantage in-game.

Again, thanks for your feedback.

-Ben

**Comment by Jmarroqu** [comment]
@bls1999 Your macro methods is bogus though. You're using 3rd party tools, 3rd party programs to find players, to clone your hats, etc yet the player can't use any? Why? Because you're a staff? That's not fair so stop saying you think it's unfair when you do the same thing and get away with it.

**Comment by FearsPR2** [comment]
@bls1999 You guys give yourselves invis set, croc set, fred set, arti hat, any item in the game that other players have to work for. You guys give yourselves 19 hats when there's only 13 available to everyone else in the game. However when we want to just relax and gain experience on our favorite flash game, now there's a problem? Quite hypocritical.

**Comment by bls1999** [comment]
Hi Colin,

1. Tools coded by Jiggmin and/or are accessible to mods and admins on PR2hub are not third-party tools.
2. Using third-party tools to catch rule-breakers in game is different from using them to gain an unfair advantage in the game.

The real reason Eternal and I have decided to give moderators 19 hats or more is so that they can easily be distinguished on a server by clicking "Hats" on the online list.  We haven't made that information public in the past, but due to the nature of your accusations I think it's fitting to release it now.

If you have any other questions, let me know and I'll do my best to answer.

-Ben

**Comment by bls1999** [comment]
Hi Fears,

The heads, bodies, and feet are given to the staff team as staff perks.  We also give them these perks so they can fairly oversee contests and not have any conflicts of interest (I.e. contest host does something that could get them removed as a host, staff member turns a blind eye because they like participating in the contest).

There are reasons behind our actions.

If you have any other questions, please let me know.
-Ben

**Comment by FearsPR2** [comment]
@bls1999 Serious question. How does giving out parts lead to a fair overseen contest? I'm not fully understanding that.

**Comment by FearsPR2** [comment]
Also my final say on this matter is that I 100% agreed with the macro ban implementation when this game was hitting 400+ players on at once. But it's gotten to the point to where that ban just isn't needed anymore.

The "unfair advantage" is outweighed by the fact that there's hardly anyone online that even races anymore. This game is about to hit 10 years old, I think letting people maximize exp gains should be allowed at this point.

**Comment by VipaPR2** [comment]
Yeah, I agree with you @FearsPR2 ^

**Comment by MagicalBoss** [comment]
I agree with Fears, if the game’s inactive as it is now, just let us enjoy macroing and ranking up without having to click every 2 minuets? Whenever I do it I usually will be at my computer but I will be doing something else like watching YouTube on another screen, it just makes it easier. I could understand why it was bannable back then but now, simmers and macroers are pretty much a third of what makes up the community (myself included).

**Comment by a7x3** [comment]
I must admit, it really does not bother me if somebody macros, and that's coming from a member of staff, I dont do it myself but considering the amount of members, I see it as a way to keep the numbers up, and like someone mentioned, it's also giving Jiggy money due to the HH's bought. Back in the day when there were hundreds online, ya that should still be an offence, but some rules I personally should be a little relaxed now considering the player count. I dont speak for all staff obviously, but I do have my own opinions on things.

**Comment by PR2SteamPower** [comment]
#UNBAN SP 

fr help me i need pr2 in my life

**Comment by jacob-grahn** [comment]
Alright, macros are now officially allowed.
